# Generated by Django 4.1.7 on 2023-06-17 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_photo', models.CharField(max_length=50)),
                ('team_name', models.CharField(max_length=50)),
                ('team_address', models.CharField(max_length=50)),
                ('team_image', models.FilePathField(path='/static/img/')),
            ],
        ),
    ]
