# Generated by Django 4.1.7 on 2023-06-17 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='team_photo',
        ),
    ]
